name: Deploy dex

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Build hardhat
        working-directory: ./hardhat
        run: |
          yarn
          yarn hardhat compile

      - name: Build DEX
        working-directory: ./apps/dex
        run: yarn build

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
